apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mytest
  name: mytest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mytest
  template:
    metadata:
      labels:
        app: mytest
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
